-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg3gLKjVzIs5DdjAol
9AqFYZsW+vvFgCHp1TJUIGy3Bc+gCgYIKoZIzj0DAQehRANCAASPgtnlCwuIKUjS
gScp/z6FmOFkZKtfFQ5hH8WAzo7GqnZh+SIledUM0EgoJCHsAY/y+hsGkFdmHj8b
QsCVGEPV
-----END PRIVATE KEY-----